import { Sport, ScheduleItem, FeatureItem, TranslationDict } from './types';

export const translations: TranslationDict = {
  navSchedule: { en: 'Schedule', mk: 'Распоред' },
  navSports: { en: 'Sports', mk: 'Спортови' },
  navFeatures: { en: 'Features', mk: 'Содржини' },
  navRegister: { en: 'Registration', mk: 'Пријавување' },
  navVenue: { en: 'Location', mk: 'Локација' },
  navGallery: { en: 'Gallery', mk: 'Галерија' },
  heroSubtitle: { en: 'Valandovo Sports Summer 2026', mk: 'Валандовско Спортско Лето 2026' },
  heroDates: { en: 'August 5 – August 9, 2026', mk: '5 – 9 Август, 2026' },
  heroLocation: { en: 'Valandovo, Macedonia', mk: 'Валандово, Македонија' },
  heroBtnRegister: { en: 'Register a Team', mk: 'Пријави Екипа' },
  heroBtnSchedule: { en: 'View Schedule', mk: 'Види Распоред' },
  countdownTitle: { en: 'The Event Starts In', mk: 'Настанот Започнува За' },
  days: { en: 'Days', mk: 'Дена' },
  hours: { en: 'Hours', mk: 'Часа' },
  minutes: { en: 'Min', mk: 'Мин' },
  seconds: { en: 'Sec', mk: 'Сек' },
  statsSports: { en: 'Sports Tournaments', mk: 'Спортски Турнири' },
  statsDays: { en: 'Days of Action', mk: 'Дена Акција' },
  statsTeams: { en: 'Sports Participants', mk: 'Спортски Учесници' },
  statsSpectators: { en: 'Spectators Expected', mk: 'Очекувани Посетители' },
  statsPrizePool: { en: 'Total Prize Pool', mk: 'Вкупен Награден Фонд' },
  sportsTitle: { en: 'Featured Tournaments', mk: 'Спортски Турнири' },
  sportsSubtitle: { en: 'Choose your sport, form a team, and compete for prestige and cash prizes.', mk: 'Одберете спорт, формирајте екипа и борете се за престиж и вредни награди.' },
  prizePoolLabel: { en: 'Prize Pool:', mk: 'Награден Фонд:' },
  maxTeamsLabel: { en: 'Max Teams:', mk: 'Макс. Екипи:' },
  registeredLabel: { en: 'Registered:', mk: 'Пријавени:' },
  entryFeeLabel: { en: 'Entry Fee:', mk: 'Котизација:' },
  btnRegisterTeam: { en: 'Register Team', mk: 'Пријави Екипа' },
  btnRegisterIndividual: { en: 'Register Player', mk: 'Пријави Играч' },
  btnMoreInfo: { en: 'More Information', mk: 'Повеќе Информации' },
  scheduleTitle: { en: 'Event Schedule', mk: 'Програма на Настанот' },
  scheduleSubtitle: { en: 'Keep track of matches, opening ceremonies, and summer vibes.', mk: 'Следете ги натпреварите, свеченото отворање и летната атмосфера.' },
  filterAll: { en: 'All Events', mk: 'Сите Настани' },
  filterMatches: { en: 'Matches', mk: 'Натпревари' },
  filterCeremonies: { en: 'Ceremonies', mk: 'Церемонии' },
  filterMusic: { en: 'Entertainment', mk: 'Забава' },
  featuresTitle: { en: 'Why Join the Event?', mk: 'Што нуди Валандовско Спортско Лето?' },
  featuresSubtitle: { en: 'An unforgettable mix of high-stakes competition, great music, and local traditions.', mk: 'Неверојатен спој на спортски натпревари, одлична музика и локални традиции.' },
  registerTitle: { en: 'Team Registration', mk: 'Пријавување Екипи' },
  registerSubtitle: { en: 'Secure a spot for your team. Fill out the registration form below.', mk: 'Обезбедете место за вашата екипа. Пополнете го образецот подолу.' },
  formSport: { en: 'Select Sport', mk: 'Изберете Спорт' },
  formTeamName: { en: 'Team Name', mk: 'Име на Екипа' },
  formCaptainName: { en: 'Captain Name (Full Name)', mk: 'Име на Капитен (Име и Презиме)' },
  formEmail: { en: 'Captain Email Address', mk: 'Е-пошта на Капитен' },
  formPhone: { en: 'Captain Phone Number', mk: 'Телефонски број на Капитен' },
  formRoster: { en: 'Player Roster (One per line)', mk: 'Список на Играчи (Еден по ред)' },
  formRosterPlaceholder: { en: 'Player 1\nPlayer 2\nPlayer 3...', mk: 'Играч 1\nИграч 2\nИграч 3...' },
  formSubmit: { en: 'Submit Registration', mk: 'Поднеси Пријава' },
  formSuccess: { en: 'Registration Submitted Successfully!', mk: 'Пријавата е успешно поднесена!' },
  formSuccessDesc: { en: 'Your team is registered. We will contact the captain soon with bracket details.', mk: 'Вашата екипа е пријавена. Набргу ќе ве контактираме со повеќе детали за ждрепката.' },
  myRegistrations: { en: 'My Registrations', mk: 'Мои Пријави' },
  noRegistrations: { en: 'No active team registrations from this browser yet.', mk: 'Сè уште немате пријавено екипи од овој прелистувач.' },
  galleryTitle: { en: 'Moments from Previous Editions', mk: 'Мигови од Минатите Изданија' },
  gallerySubtitle: { en: 'Relive the high-octane action, sportsmanship, and incredible community atmosphere from our past tournaments.', mk: 'Погледнете ја жешката атмосфера, спортскиот дух и незаборавните моменти од претходните години.' },
  galleryFilterAll: { en: 'All Photos', mk: 'Сите Фотографии' },
  galleryFilterBasketball: { en: 'Basketball', mk: 'Кошарка' },
  galleryFilterFootball: { en: 'Football', mk: 'Фудбал' },
  galleryFilterAtmosphere: { en: 'Atmosphere', mk: 'Атмосфера' },
  galleryFilterWinners: { en: 'Winners', mk: 'Победници' },
  galleryPlaceholderNote: { en: 'Template Ready: Replace these placeholders with your real photos from Valandovo.', mk: 'Шаблонот е подготвен: Заменете ги овие слики со ваши вистински слики од Валандово.' },
  venueTitle: { en: 'The Location & Courts', mk: 'Локација и Терени' },
  venueSubtitle: { en: 'Located in the heart of Valandovo, near iconic landmarks and modern sports complexes.', mk: 'Сместено во срцето на Валандово, веднаш до значајните обележја и спортски комплекси.' },
  venueLocationLabel: { en: 'Josip Broz Tito Elementary School Area', mk: 'ОУ „Јосип Броз Тито“' },
  venueDesc: { en: 'The tournament will be hosted on the fields and outdoor courts of the "Josip Broz Tito" elementary school. In addition, the school\'s fully-equipped closed sports gym will be utilized for indoor tournament matches and activities, providing premium facilities for all participating athletes and teams.', mk: 'Турнирот ќе се одржи на терените и игралиштата на основното училиште „Јосип Броз Тито“. Дополнително, затворената спортска сала на училиштето ќе биде целосно искористена за потребите на натпреварите, нудејќи одлични услови за сите учесници.' },
  footerDesc: { en: 'Valandovosko Leto is the premier summer sport event of South-Eastern Macedonia, organized by GG3x3 and Municipality of Valandovo with additional support of sponsors and local contributors.', mk: 'Валандовско Спортско Лето е најголемиот спортски настан во југоисточниот дел на Македонија, организиран од GG3x3 и Општина Валандово со дополнителна поддршка од спонзори и локални помагатели.' },
  rightsReserved: { en: 'All Rights Reserved.', mk: 'Сите права се задржани.' },
  organizerLabel: { en: 'Organizers:', mk: 'Организатори:' },
  contactLabel: { en: 'Contact Us:', mk: 'Контакт:' },
  capacityFilled: { en: 'Capacity Filled', mk: 'Капацитетот е пополнет' },
  registrationClosed: { en: 'Registration Closed', mk: 'Пријавувањето е затворено' },
};

export const sportsData: Sport[] = [
  {
    id: 'basketball',
    nameEn: '3x3 Basketball',
    nameMk: '3х3 Баскет',
    iconName: 'Dribbble',
    detailsEn: 'The core flagship tournament of the summer, played under FIBA 3x3 rules. Highly dynamic, with professional referees, cash prizes, and individual awards.',
    detailsMk: 'Главниот турнир на летото, кој се игра според официјалните FIBA 3х3 правила. Многу динамичен, со професионални судии, парични награди и индивидуални признанија.',
    maxTeams: 16,
    prizePoolEn: '€2,850+',
    prizePoolMk: '175,000 MKD+',
    registeredCount: 6,
    entryFeeEn: '€80',
    entryFeeMk: '5,000 MKD',
  },
  {
    id: 'soccer',
    nameEn: 'Futsal',
    nameMk: 'Мал Фудбал',
    iconName: 'Footprints',
    detailsEn: 'Futsal tournament played on high-grade plastic courts. 5+1 setup. Thrilling matches and immense crowd support during hot summer nights.',
    detailsMk: 'Турнир во мал фудбал на тврда подлога. Систем 5+1. Возбудливи натпревари со силна поддршка од публиката во топлите летни вечери.',
    maxTeams: 12,
    prizePoolEn: '€3,600+',
    prizePoolMk: '220,000 MKD+',
    registeredCount: 5,
    entryFeeEn: '€80',
    entryFeeMk: '5,000 MKD',
  },
  {
    id: 'tennis',
    nameEn: 'Tennis',
    nameMk: 'Тенис',
    iconName: 'Target',
    detailsEn: 'Singles tournament on outdoor hard courts. Format consists of group stages followed by a single-elimination knockout bracket.',
    detailsMk: 'Турнир во сингл машка/женска конкуренција на тврда подлога. Формат со групна фаза проследена со елиминации во нокаут фаза.',
    maxTeams: 16,
    prizePoolEn: '€450+',
    prizePoolMk: '28,000 MKD+',
    registeredCount: 8,
    entryFeeEn: '€20',
    entryFeeMk: '1,200 MKD',
  },
  {
    id: 'handball',
    nameEn: 'Handball',
    nameMk: 'Ракомет',
    iconName: 'Hand',
    detailsEn: "Dynamic handball cup with top regional teams. Played under standard IHF rules in the school's indoor gym.",
    detailsMk: 'Динамичен ракометен куп во училишната спортска сала со најдобрите екипи во регионот. Се игра според стандардни ракометни правила.',
    maxTeams: 6,
    prizePoolEn: '€300+',
    prizePoolMk: '18,000 MKD+',
    registeredCount: 4,
    entryFeeEn: '€18',
    entryFeeMk: '1,000 MKD',
  },
  {
    id: 'volleyball',
    nameEn: "Volleyball Women's",
    nameMk: 'Женска Одбојка',
    iconName: 'Volleyball',
    detailsEn: "Women's volleyball tournament with a magnificent summer setting. Fast, exciting, and completely free of charge to play.",
    detailsMk: 'Одбојкарски турнир со жешка летна атмосфера на одбојкарските терени, наменет за женски екипи. Брзо, забавно и целосно бесплатно за сите.',
    maxTeams: 4,
    prizePoolEn: '€450+',
    prizePoolMk: '28,000 MKD+',
    registeredCount: 4,
    entryFeeEn: 'Free',
    entryFeeMk: 'Бесплатно',
  },
  {
    id: 'pingpong',
    nameEn: 'Table Tennis',
    nameMk: 'Пинг Понг',
    iconName: 'CircleDot',
    detailsEn: 'Table tennis singles tournament open to all ages and skill levels. High-intensity fast-paced table matches.',
    detailsMk: 'Турнир во пинг-понг во сингл конкуренција, отворен за сите генерации и нивоа на вештина. Брза и прецизна игра.',
    maxTeams: 32,
    prizePoolEn: '€325+',
    prizePoolMk: '20,000 MKD+',
    registeredCount: 14,
    entryFeeEn: '€13',
    entryFeeMk: '800 MKD',
  },
];

export const scheduleData: ScheduleItem[] = [
  // Day 1 - Aug 5
  {
    id: 's2',
    time: 'Hours TBD',
    date: '2026-08-05',
    titleEn: 'Futsal Tournament - Group Stage',
    titleMk: 'Турнир во Мал Фудбал - Групна Фаза',
    locationEn: 'Main Futsal Court',
    locationMk: 'Терен за мал фудбал',
    sportId: 'soccer',
    type: 'match',
  },
  {
    id: 's3',
    time: 'Hours TBD',
    date: '2026-08-05',
    titleEn: 'Tennis Singles Tournament - Matches',
    titleMk: 'Турнир во Тенис - Натпревари',
    locationEn: 'Tennis Courts',
    locationMk: 'Тениски Терени',
    sportId: 'tennis',
    type: 'match',
  },
  // Day 2 - Aug 6
  {
    id: 's5',
    time: 'Hours TBD',
    date: '2026-08-06',
    titleEn: 'Volleyball Women’s Tournament - Matches',
    titleMk: 'Турнир во Женска Одбојка - Натпревари',
    locationEn: 'Volleyball Field',
    locationMk: 'Одбојкарско игралиште',
    sportId: 'volleyball',
    type: 'match',
  },
  {
    id: 's6',
    time: 'Hours TBD',
    date: '2026-08-06',
    titleEn: 'Futsal Tournament - Group Stage',
    titleMk: 'Турнир во Мал Фудбал - Групна Фаза',
    locationEn: 'Main Futsal Court',
    locationMk: 'Терен за мал фудбал',
    sportId: 'soccer',
    type: 'match',
  },
  {
    id: 's7',
    time: 'Hours TBD',
    date: '2026-08-06',
    titleEn: 'Tennis Singles Tournament - Matches',
    titleMk: 'Турнир во Тенис - Натпревари',
    locationEn: 'Tennis Courts',
    locationMk: 'Тениски Терени',
    sportId: 'tennis',
    type: 'match',
  },

  // Day 3 - Aug 7
  {
    id: 's8',
    time: 'Hours TBD',
    date: '2026-08-07',
    titleEn: 'Handball Cup - Full Tournament',
    titleMk: 'Ракометен Куп - Целосен Турнир',
    locationEn: 'School Indoor Gym',
    locationMk: 'Училишна спортска сала',
    sportId: 'handball',
    type: 'match',
  },
  {
    id: 's9',
    time: 'Hours TBD',
    date: '2026-08-07',
    titleEn: 'Futsal Tournament - Quarter Finals',
    titleMk: 'Турнир во Мал Фудбал - Четвртфинале',
    locationEn: 'Main Futsal Court',
    locationMk: 'Терен за мал фудбал',
    sportId: 'soccer',
    type: 'match',
  },
  {
    id: 's10',
    time: 'Hours TBD',
    date: '2026-08-07',
    titleEn: 'Tennis Singles Tournament - Matches',
    titleMk: 'Турнир во Тенис - Натпревари',
    locationEn: 'Tennis Courts',
    locationMk: 'Тениски Терени',
    sportId: 'tennis',
    type: 'match',
  },
  // Day 4 - Aug 8
  {
    id: 's12',
    time: 'Hours TBD',
    date: '2026-08-08',
    titleEn: '3x3 Basketball Tournament - Matches',
    titleMk: 'Турнир во 3х3 Баскет - Натпревари',
    locationEn: 'Main Basketball Court',
    locationMk: 'Терен за Баскет',
    sportId: 'basketball',
    type: 'match',
  },
  {
    id: 's13',
    time: 'Hours TBD',
    date: '2026-08-08',
    titleEn: 'Futsal Tournament - Semi Finals',
    titleMk: 'Турнир во Мал Фудбал - Полуфинале',
    locationEn: 'Main Futsal Court',
    locationMk: 'Терен за мал фудбал',
    sportId: 'soccer',
    type: 'match',
  },
  {
    id: 's14',
    time: 'Hours TBD',
    date: '2026-08-08',
    titleEn: 'Tennis Singles Tournament - Matches',
    titleMk: 'Турнир во Тенис - Натпревари',
    locationEn: 'Tennis Courts',
    locationMk: 'Тениски Терени',
    sportId: 'tennis',
    type: 'match',
  },

  // Day 5 - Aug 9
  {
    id: 's15',
    time: 'Hours TBD',
    date: '2026-08-09',
    titleEn: 'Table Tennis Tournament - Full Tournament',
    titleMk: 'Турнир во Пинг Понг - Целосен Турнир',
    locationEn: 'Municipal Sports Hall',
    locationMk: 'Општинска Спортска Сала',
    sportId: 'pingpong',
    type: 'match',
  },
  {
    id: 's16',
    time: 'Hours TBD',
    date: '2026-08-09',
    titleEn: '3x3 Basketball - Knockout & Finals',
    titleMk: '3х3 Баскет - Елиминации и Финале',
    locationEn: 'Main Basketball Court',
    locationMk: 'Терен за Баскет',
    sportId: 'basketball',
    type: 'match',
  },
  {
    id: 's17',
    time: 'Hours TBD',
    date: '2026-08-09',
    titleEn: 'Futsal Tournament - 3rd Place & Grand Final',
    titleMk: 'Мал Фудбал - Натпревар за 3-то Место и Големо Финале',
    locationEn: 'Main Futsal Court',
    locationMk: 'Терен за мал фудбал',
    sportId: 'soccer',
    type: 'match',
  },
  {
    id: 's18',
    time: 'Hours TBD',
    date: '2026-08-09',
    titleEn: 'Tennis Singles Tournament - Finals',
    titleMk: 'Турнир во Тенис - Финални Борби',
    locationEn: 'Tennis Courts',
    locationMk: 'Тениски Терени',
    sportId: 'tennis',
    type: 'match',
  }
];

export const featuresData: FeatureItem[] = [
  {
    id: 'f1',
    titleEn: 'Under the lights Matches',
    titleMk: 'Натпревари под Рефлектори',
    descEn: 'Beat the southern Macedonian summer heat! All major tournament playoffs are scheduled in the cooler evening hours under state-of-the-art night lighting.',
    descMk: 'Избегнете ја летната горештина! Сите главни натпревари се играат во свежите вечерни часови под професионално рефлекторско осветлување.',
    iconName: 'Moon',
  },
  {
    id: 'f2',
    titleEn: 'Summer Beats & Vibe',
    titleMk: 'Летни Ритми и Музика',
    descEn: 'Enjoy outstanding summer music playlists, custom sounds, and acoustic background sessions to keep the energy high and the crowd engaged throughout the warm nights.',
    descMk: 'Уживајте во одлична летна музика, пријатно озвучување и акустични звуци кои ќе направат незаборавна атмосфера на спортските терени.',
    iconName: 'Music',
  },
  {
    id: 'f3',
    titleEn: 'Local Cuisine & Wine',
    titleMk: 'Локална Храна и Вино',
    descEn: 'Valandovo is famous for its warm climate, pomegranates, and outstanding wines. Enjoy our food stalls offering delicious regional specialties.',
    descMk: 'Валандово е познато по топлиот климат, калинките и извонредните вина. Пробајте од храната на нашите штандови со локални специјалити.',
    iconName: 'Utensils',
  },
  {
    id: 'f4',
    titleEn: 'Solid Cash Prizes',
    titleMk: 'Вредни Парични Награди',
    descEn: 'Compete for robust prizes across multiple divisions, alongside custom-crafted trophies, medals, and premium gear from tournament sponsors.',
    descMk: 'Борете се за големиот фонд на награди во повеќе категории, заедно со уникатни пехари, медали и квалитетна спортска опрема.',
    iconName: 'Coins',
  },
];

export const SHOW_SCHEDULE = true;
export const SHOW_FULL_SCHEDULE = true;
